version: "2"

plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php, inc, lib"
      standard: "PSR1,PSR2"
      file_extensions: "php,inc,lib"
      standard: "PSR1,PSR2"
exclude_patterns:
  - ".git"
  - "vendor"
  - "tests"
